<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
        <Version>2.1.1</Version>
        <Authors>Antstar609</Authors>

        <PublishAot>true</PublishAot>
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
        <TrimMode>link</TrimMode>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.4" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.4" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.4">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="MessageBox.Avalonia" Version="3.2.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>

        <TrimmerRootAssembly Include="Avalonia.Themes.Fluent"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\1529_Champ_Fleury.ttf"/>
        <AvaloniaResource Include="Assets\1529_Champ_Fleury.ttf"/>
        <None Remove="Assets\modding_eula.txt"/>
        <AvaloniaResource Include="Assets\modding_eula.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AvaloniaResource>
        <None Remove="Assets\icon.ico"/>
        <AvaloniaResource Include="Assets\icon.ico"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="KCD-Mod-Packer-Legacy\**"/>
        <AvaloniaResource Remove="KCD-Mod-Packer-Legacy\**"/>
        <AvaloniaXaml Remove="KCD-Mod-Packer-Legacy\**"/>
        <Compile Remove="KCD-Mod-Packer-Legacy\**"/>
        <EmbeddedResource Remove="KCD-Mod-Packer-Legacy\**"/>
        <AdditionalFiles Remove="KCD-Mod-Packer-Legacy\**"/>
    </ItemGroup>
</Project>
